# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.CONFIG_MAP_NAME }}
  namespace: default
data:
  EMBEDDING_MODEL_ID: {{ .Values.config.EMBEDDING_MODEL_ID }}
  HUGGINGFACEHUB_API_TOKEN: {{ .Values.config.HUGGINGFACEHUB_API_TOKEN }}
  NODE_SELECTOR: {{ .Values.config.NODE_SELECTOR }}
  RERANK_MODEL_ID: {{ .Values.config.RERANK_MODEL_ID }}
  LLM_MODEL_ID: {{ .Values.config.LLM_MODEL_ID }}
  REDIS_URL: redis://vector-db.default.svc.cluster.local:6379
  RERANK_SERVER_HOST_IP: reranking-dependency-svc
  RETRIEVER_SERVICE_HOST_IP: retriever-svc
  LLM_SERVER_HOST_IP: llm-dependency-svc
  INDEX_NAME: rag-redis
  EMBEDDING_SERVER_HOST_IP: embedding-dependency-svc
  TEI_ENDPOINT: http://embedding-dependency-svc.default.svc.cluster.local:6006
  LLM_SERVER_PORT: "9009"
  RERANK_SERVER_PORT: "8808"
  EMBEDDING_SERVER_PORT: "6006"
---
