# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Default values for retriever-usvc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

tei:
  enabled: true
redis-vector-db:
  enabled: true
milvus:
  enabled: false
