
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version: "3.8"

services:
  whisper-service:
    image: ${REGISTRY:-opea}/whisper-gaudi:${TAG:-latest}
    container_name: whisper-service
    ports:
      - "7066:7066"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HABANA_VISIBLE_DEVICES: all
      OMPI_MCA_btl_vader_single_copy_mechanism: none
    runtime: habana
    cap_add:
      - SYS_NICE
    restart: unless-stopped
  speecht5-service:
    image: ${REGISTRY:-opea}/speecht5-gaudi:${TAG:-latest}
    container_name: speecht5-service
    ports:
      - "7055:7055"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HABANA_VISIBLE_DEVICES: all
      OMPI_MCA_btl_vader_single_copy_mechanism: none
    runtime: habana
    cap_add:
      - SYS_NICE
    restart: unless-stopped
  tgi-service:
    image: ghcr.io/huggingface/tgi-gaudi:2.0.6
    container_name: tgi-gaudi-server
    ports:
      - "3006:80"
    volumes:
      - "./data:/data"
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HUGGING_FACE_HUB_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      HF_HUB_DISABLE_PROGRESS_BARS: 1
      HF_HUB_ENABLE_HF_TRANSFER: 0
      HABANA_VISIBLE_DEVICES: all
      OMPI_MCA_btl_vader_single_copy_mechanism: none
      ENABLE_HPU_GRAPH: true
      LIMIT_HPU_GRAPH: true
      USE_FLASH_ATTENTION: true
      FLASH_ATTENTION_RECOMPUTE: true
    runtime: habana
    cap_add:
      - SYS_NICE
    ipc: host
    command: --model-id ${LLM_MODEL_ID} --max-input-length 128 --max-total-tokens 256
  wav2lip-service:
    image: ${REGISTRY:-opea}/wav2lip-gaudi:${TAG:-latest}
    container_name: wav2lip-service
    ports:
      - "7860:7860"
    ipc: host
    volumes:
      - ${PWD}:/outputs
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HABANA_VISIBLE_DEVICES: all
      OMPI_MCA_btl_vader_single_copy_mechanism: none
      DEVICE: ${DEVICE}
      INFERENCE_MODE: ${INFERENCE_MODE}
      CHECKPOINT_PATH: ${CHECKPOINT_PATH}
      FACE: ${FACE}
      AUDIO: ${AUDIO}
      FACESIZE: ${FACESIZE}
      OUTFILE: ${OUTFILE}
      GFPGAN_MODEL_VERSION: ${GFPGAN_MODEL_VERSION}
      UPSCALE_FACTOR: ${UPSCALE_FACTOR}
      FPS: ${FPS}
      WAV2LIP_PORT: ${WAV2LIP_PORT}
    runtime: habana
    cap_add:
      - SYS_NICE
    restart: unless-stopped
  animation:
    image: ${REGISTRY:-opea}/animation:${TAG:-latest}
    container_name: animation-gaudi-server
    ports:
      - "3008:9066"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HABANA_VISIBLE_DEVICES: all
      OMPI_MCA_btl_vader_single_copy_mechanism: none
      WAV2LIP_ENDPOINT: ${WAV2LIP_ENDPOINT}
    runtime: habana
    cap_add:
      - SYS_NICE
    restart: unless-stopped
  avatarchatbot-gaudi-backend-server:
    image: ${REGISTRY:-opea}/avatarchatbot:${TAG:-latest}
    container_name: avatarchatbot-gaudi-backend-server
    depends_on:
      - animation
    ports:
      - "3009:8888"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
      - MEGA_SERVICE_HOST_IP=${MEGA_SERVICE_HOST_IP}
      - MEGA_SERVICE_PORT=${MEGA_SERVICE_PORT}
      - WHISPER_SERVER_HOST_IP=${WHISPER_SERVER_HOST_IP}
      - WHISPER_SERVER_PORT=${WHISPER_SERVER_PORT}
      - LLM_SERVER_HOST_IP=${LLM_SERVER_HOST_IP}
      - LLM_SERVER_PORT=${LLM_SERVER_PORT}
      - SPEECHT5_SERVER_HOST_IP=${SPEECHT5_SERVER_HOST_IP}
      - SPEECHT5_SERVER_PORT=${SPEECHT5_SERVER_PORT}
      - ANIMATION_SERVICE_HOST_IP=${ANIMATION_SERVICE_HOST_IP}
      - ANIMATION_SERVICE_PORT=${ANIMATION_SERVICE_PORT}
    ipc: host
    restart: always

networks:
  default:
    driver: bridge
