# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# this file should be run in the root of the repo
services:
  dataprep-redis:
    build:
      dockerfile: comps/dataprep/redis/langchain/Dockerfile
    image: ${REGISTRY:-opea}/dataprep-redis:${TAG:-latest}
  dataprep-qdrant:
    build:
      dockerfile: comps/dataprep/qdrant/langchain/Dockerfile
    image: ${REGISTRY:-opea}/dataprep-qdrant:${TAG:-latest}
  dataprep-on-ray-redis:
    build:
      dockerfile: comps/dataprep/redis/langchain_ray/Dockerfile
    image: ${REGISTRY:-opea}/dataprep-on-ray-redis:${TAG:-latest}
  dataprep-multimodal-vdms:
    build:
      dockerfile: comps/dataprep/vdms/multimodal_langchain/Dockerfile
    image: ${REGISTRY:-opea}/dataprep-multimodal-vdms:${TAG:-latest}
  dataprep-multimodal-redis:
    build:
      dockerfile: comps/dataprep/multimodal/redis/langchain/Dockerfile
    image: ${REGISTRY:-opea}/dataprep-multimodal-redis:${TAG:-latest}
  dataprep-redis-llama-index:
    build:
      dockerfile: comps/dataprep/redis/llama_index/Dockerfile
    image: ${REGISTRY:-opea}/dataprep-redis-llama-index:${TAG:-latest}
  dataprep-milvus:
    build:
      dockerfile: comps/dataprep/milvus/langchain/Dockerfile
    image: ${REGISTRY:-opea}/dataprep-milvus:${TAG:-latest}
  dataprep-pgvector:
    build:
      dockerfile: comps/dataprep/pgvector/langchain/Dockerfile
    image: ${REGISTRY:-opea}/dataprep-pgvector:${TAG:-latest}
  dataprep-pinecone:
    build:
      dockerfile: comps/dataprep/pinecone/langchain/Dockerfile
    image: ${REGISTRY:-opea}/dataprep-pinecone:${TAG:-latest}
  dataprep-vdms:
    build:
      dockerfile: comps/dataprep/vdms/langchain/Dockerfile
    image: ${REGISTRY:-opea}/dataprep-vdms:${TAG:-latest}
  dataprep-neo4j:
    build:
      dockerfile: comps/dataprep/neo4j/langchain/Dockerfile
    image: ${REGISTRY:-opea}/dataprep-neo4j:${TAG:-latest}
  dataprep-neo4j-llamaindex:
    build:
      dockerfile: comps/dataprep/neo4j/llama_index/Dockerfile
    image: ${REGISTRY:-opea}/dataprep-neo4j-llamaindex:${TAG:-latest}
  dataprep-multimedia2text:
    build:
      dockerfile: comps/dataprep/multimedia2text/Dockerfile
    image: ${REGISTRY:-opea}/dataprep-multimedia2text:${TAG:-latest}
  dataprep-video2audio:
    build:
      dockerfile: comps/dataprep/multimedia2text/video2audio/Dockerfile
    image: ${REGISTRY:-opea}/dataprep-video2audio:${TAG:-latest}
  dataprep-audio2text:
    build:
      dockerfile: comps/dataprep/multimedia2text/audio2text/Dockerfile
    image: ${REGISTRY:-opea}/dataprep-audio2text:${TAG:-latest}
