# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# this file should be run in the root of the repo
# images used by GenAIExamples: guardrails-tgi
# others: guardrails-pii-detection
services:
  guardrails-tgi:
    build:
      dockerfile: comps/guardrails/llama_guard/langchain/Dockerfile
    image: ${REGISTRY:-opea}/guardrails-tgi:${TAG:-latest}

  guardrails-bias-detection:
    build:
      dockerfile: comps/guardrails/bias_detection/Dockerfile
    image: ${REGISTRY:-opea}/guardrails-bias-detection:${TAG:-latest}

  guardrails-toxicity-detection:
    build:
      dockerfile: comps/guardrails/toxicity_detection/Dockerfile
    image: ${REGISTRY:-opea}/guardrails-toxicity-detection:${TAG:-latest}
