# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# this file should be run in the root of the repo
services:
  guardrails:
    build:
      dockerfile: comps/guardrails/src/guardrails/Dockerfile
    image: ${REGISTRY:-opea}/guardrails:${TAG:-latest}
  guardrails-bias-detection:
    build:
      dockerfile: comps/guardrails/src/bias_detection/Dockerfile
    image: ${REGISTRY:-opea}/guardrails-bias-detection:${TAG:-latest}
  guardrails-pii-predictionguard:
    build:
      dockerfile: comps/guardrails/src/pii_detection/Dockerfile
    image: ${REGISTRY:-opea}/guardrails-pii-predictionguard:${TAG:-latest}
  guardrails-toxicity-predictionguard:
    build:
      dockerfile: comps/guardrails/src/toxicity_detection/Dockerfile
    image: ${REGISTRY:-opea}/guardrails-toxicity-predictionguard:${TAG:-latest}
  guardrails-factuality-predictionguard:
    build:
      dockerfile: comps/guardrails/src/factuality_alignment/Dockerfile
    image: ${REGISTRY:-opea}/guardrails-factuality-predictionguard:${TAG:-latest}
  guardrails-injection-predictionguard:
    build:
      dockerfile: comps/guardrails/src/prompt_injection/Dockerfile
    image: ${REGISTRY:-opea}/guardrails-injection-predictionguard:${TAG:-latest}
