# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# this file should be run in the root of the repo
services:
  guardrails-tgi:
    build:
      dockerfile: comps/guardrails/llama_guard/langchain/Dockerfile
    image: ${REGISTRY:-opea}/guardrails-tgi:${TAG:-latest}
  guardrails-pii-detection:
    build:
      dockerfile: comps/guardrails/pii_detection/Dockerfile
    image: ${REGISTRY:-opea}/guardrails-pii-detection:${TAG:-latest}
  guardrails-bias-detection:
    build:
      dockerfile: comps/guardrails/bias_detection/Dockerfile
    image: ${REGISTRY:-opea}/guardrails-bias-detection:${TAG:-latest}
  guardrails-toxicity-detection:
    build:
      dockerfile: comps/guardrails/toxicity_detection/Dockerfile
    image: ${REGISTRY:-opea}/guardrails-toxicity-detection:${TAG:-latest}
  guardrails-wildguard:
    build:
      dockerfile: comps/guardrails/wildguard/langchain/Dockerfile
    image: ${REGISTRY:-opea}/guardrails-wildguard:${TAG:-latest}
  guardrails-pii-detection-predictionguard:
    build:
      dockerfile: comps/guardrails/pii_detection/predictionguard/Dockerfile
    image: ${REGISTRY:-opea}/guardrails-pii-predictionguard:${TAG:-latest}
  guardrails-toxicity-detection-predictionguard:
    build:
      dockerfile: comps/guardrails/toxicity_detection/predictionguard/Dockerfile
    image: ${REGISTRY:-opea}/guardrails-toxicity-predictionguard:${TAG:-latest}
  guardrails-factuality-predictionguard:
    build:
      dockerfile: comps/guardrails/factuality/predictionguard/Dockerfile
    image: ${REGISTRY:-opea}/guardrails-factuality-predictionguard:${TAG:-latest}
  guardrails-injection-predictionguard:
    build:
      dockerfile: comps/guardrails/prompt_injection/predictionguard/Dockerfile
    image: ${REGISTRY:-opea}/guardrails-injection-predictionguard:${TAG:-latest}
