# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# this file should be run in the root of the repo
services:
  image2image:
    build:
      dockerfile: comps/image2image/Dockerfile
    image: ${REGISTRY:-opea}/image2image:${TAG:-latest}
  image2image-gaudi:
    build:
      dockerfile: comps/image2image/Dockerfile.intel_hpu
    image: ${REGISTRY:-opea}/image2image-gaudi:${TAG:-latest}
