# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# this file should be run in the root of the repo
services:
  llm-textgen:
    build:
      dockerfile: comps/llms/src/text-generation/Dockerfile
    image: ${REGISTRY:-opea}/llm-textgen:${TAG:-latest}
  llm-ollama:
    build:
      dockerfile: comps/llms/text-generation/ollama/langchain/Dockerfile
    image: ${REGISTRY:-opea}/llm-ollama:${TAG:-latest}
  llm-docsum:
    build:
      dockerfile: comps/llms/src/doc-summarization/Dockerfile
    image: ${REGISTRY:-opea}/llm-docsum-tgi:${TAG:-latest}
  llm-faqgen:
    build:
      dockerfile: comps/llms/src/faq-generation/Dockerfile
    image: ${REGISTRY:-opea}/llm-faqgen:${TAG:-latest}
  llm-native:
    build:
      dockerfile: comps/llms/text-generation/native/langchain/Dockerfile
    image: ${REGISTRY:-opea}/llm-native:${TAG:-latest}
  llm-native-llamaindex:
    build:
      dockerfile: comps/llms/text-generation/native/llama_index/Dockerfile
    image: ${REGISTRY:-opea}/llm-native-llamaindex:${TAG:-latest}
  vllm-openvino:
    build:
      context: vllm-openvino
      dockerfile: Dockerfile.openvino
    image: ${REGISTRY:-opea}/vllm-openvino:${TAG:-latest}
  vllm-gaudi:
    build:
      context: vllm-fork
      dockerfile: Dockerfile.hpu
    shm_size: '128g'
    image: ${REGISTRY:-opea}/vllm-gaudi:${TAG:-latest}
  vllm-arc:
    build:
      dockerfile: comps/llms/text-generation/vllm/langchain/dependency/Dockerfile.intel_gpu
    image: ${REGISTRY:-opea}/vllm-arc:${TAG:-latest}
  llm-eval:
    build:
      dockerfile: comps/llms/utils/lm-eval/Dockerfile
    image: ${REGISTRY:-opea}/llm-eval:${TAG:-latest}
