# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# this file should be run in the root of the repo
services:
  nginx:
    build:
      dockerfile: comps/nginx/Dockerfile
    image: ${REGISTRY:-opea}/nginx:${TAG:-latest}
