# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  reranking-fastrag:
    build:
      dockerfile: comps/reranks/fastrag/Dockerfile
    image: ${REGISTRY:-opea}/reranking-fastrag:${TAG:-latest}
  reranking-langchain-mosec-endpoint:
    build:
      dockerfile: comps/reranks/mosec/langchain/dependency/Dockerfile
    image: ${REGISTRY:-opea}/reranking-langchain-mosec-endpoint:${TAG:-latest}
  reranking-langchain-mosec:
    build:
      dockerfile: comps/reranks/mosec/langchain/Dockerfile
    image: ${REGISTRY:-opea}/reranking-langchain-mosec:${TAG:-latest}
  reranking-mosec-neural-speed:
    build:
      dockerfile: comps/reranks/neural-speed/docker/Dockerfile
    image: ${REGISTRY:-opea}/reranking-mosec-neural-speed:${TAG:-latest}
  reranking-mosec-neural-speed-endpoint:
    build:
      dockerfile: comps/reranks/neural-speed/neuralspeed-docker/Dockerfile
    image: ${REGISTRY:-opea}/reranking-mosec-neural-speed-endpoint:${TAG:-latest}
