# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# this file should be run in the root of the repo
# images used by GenAIExamples: reranking-tei
services:
  reranking-tei:
    build:
      dockerfile: comps/reranks/tei/Dockerfile
    image: ${REGISTRY:-opea}/reranking-tei:${TAG:-latest}
