# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# this file should be run in the root of the repo
services:
  retriever-pgvector:
    build:
      dockerfile: comps/retrievers/pgvector/langchain/Dockerfile
    image: ${REGISTRY:-opea}/retriever-qdrant:${TAG:-latest}
  retriever-pinecone:
    build:
      dockerfile: comps/retrievers/pinecone/langchain/Dockerfile
    image: ${REGISTRY:-opea}/retriever-pinecone:${TAG:-latest}
  retriever-milvus:
    build:
      dockerfile: comps/retrievers/milvus/langchain/Dockerfile
    image: ${REGISTRY:-opea}/retriever-milvus:${TAG:-latest}
  retriever-redis-llamaindex:
    build:
      dockerfile: comps/retrievers/redis/llama_index/Dockerfile
    image: ${REGISTRY:-opea}/retriever-redis-llamaindex:${TAG:-latest}
  retriever-pathway:
    build:
      dockerfile: comps/retrievers/pathway/langchain/Dockerfile
    image: ${REGISTRY:-opea}/retriever-pathway:${TAG:-latest}
  retriever-neo4j:
    build:
      dockerfile: comps/retrievers/neo4j/langchain/Dockerfile
    image: ${REGISTRY:-opea}/retriever-neo4j:${TAG:-latest}
