# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# this file should be run in the root of the repo
services:
  tts:
    build:
      dockerfile: comps/tts/speecht5/Dockerfile
    image: ${REGISTRY:-opea}/tts:${TAG:-latest}
  speecht5:
    build:
      dockerfile: comps/tts/speecht5/dependency/Dockerfile
    image: ${REGISTRY:-opea}/speecht5:${TAG:-latest}
  speecht5-gaudi:
    build:
      dockerfile: comps/tts/speecht5/dependency/Dockerfile.intel_hpu
    image: ${REGISTRY:-opea}/speecht5-gaudi:${TAG:-latest}
  gpt-sovits:
    build:
      dockerfile: comps/tts/gpt-sovits/Dockerfile
    image: ${REGISTRY:-opea}/gpt-sovits:${TAG:-latest}
