# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# this file should be run in the root of the repo
services:
  vectorstore-pathway:
    build:
      dockerfile: comps/vectorstores/pathway/Dockerfile
    image: ${REGISTRY:-opea}/vectorstore-pathway:${TAG:-latest}
