# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# this file should be run in the root of the repo
services:
  web-retriever-chroma:
    build:
      dockerfile: comps/web_retrievers/chroma/langchain/Dockerfile
    image: ${REGISTRY:-opea}/web-retriever-chroma:${TAG:-latest}
