# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

x-common-environment:
  &common-env
  no_proxy: ${no_proxy}
  http_proxy: ${http_proxy}
  https_proxy: ${https_proxy}

services:
  vllm-gaudi-server:
    image: opea/vllm-gaudi:1.22.0
    container_name: vllm-gaudi-server
    ports:
      - ${LLM_ENDPOINT_PORT:-8008}:80
    volumes:
      - "${DATA_PATH:-./data}:/data"
    environment:
      <<: *common-env
      HF_TOKEN: ${HF_TOKEN}
      HF_HOME: /data
      HABANA_VISIBLE_DEVICES: all
      OMPI_MCA_btl_vader_single_copy_mechanism: none
      LLM_MODEL_ID: ${LLM_MODEL_ID}
      VLLM_TORCH_PROFILER_DIR: "/mnt"
      VLLM_SKIP_WARMUP: true
      PT_HPU_ENABLE_LAZY_COLLECTIVES: true
    runtime: habana
    cap_add:
      - SYS_NICE
    ipc: host
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 150
    command: --model $LLM_MODEL_ID --tensor-parallel-size $NUM_CARDS --host 0.0.0.0 --port 80 --max-seq-len-to-capture $MAX_TOTAL_TOKENS

  browser-use-agent-server:
    image: ${REGISTRY:-opea}/browser-use-agent:${TAG:-latest}
    container_name: browser-use-agent-server
    depends_on:
      - vllm-gaudi-server
    ports:
      - ${BROWSER_USE_AGENT_PORT:-8022}:8022
    environment:
      <<: *common-env
      LLM_ENDPOINT: ${LLM_ENDPOINT-http://0.0.0.0:8008}
      LLM_MODEL: ${LLM_MODEL_ID-Qwen/Qwen2-VL-72B-Instruct}
    ipc: host
