# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  tgi-service:
    image: ghcr.io/huggingface/text-generation-inference:2.4.0-intel-cpu
    container_name: tgi-service
    ports:
      - "${TGI_PORT}:80"
    volumes:
      - "${MODEL_CACHE:-./data}:/data"
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HF_TOKEN: ${HF_TOKEN}
    shm_size: 1g
    command: --model-id ${LLM_MODEL_ID}

  postgres:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5442:5432'
    volumes:
      - ./chinook.sql:/docker-entrypoint-initdb.d/chinook.sql

  text2sql-service:
    image: ${REGISTRY:-opea}/text2query-sql:${TAG:-latest}
    container_name: text2sql-service
    ports:
      - "${TEXT2SQL_PORT}:9097"
    environment:
      - TGI_LLM_ENDPOINT=${TGI_LLM_ENDPOINT}
      - TEXT2QUERY_COMPONENT_NAME=OPEA_TEXT2QUERY_SQL
    depends_on:
      - tgi-service
      - postgres

  dbqna-xeon-react-ui-server:
    image: ${REGISTRY:-opea}/text2sql-react-ui:${TAG:-latest}
    container_name: dbqna-xeon-react-ui-server
    depends_on:
      - text2sql-service
    ports:
      - "5174:80"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
      - APP_TEXT_TO_SQL_URL=http://${host_ip}:${TEXT2SQL_PORT}/v1
    ipc: host
    restart: always


networks:
  default:
    driver: bridge
