
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version: "3.8"

services:
  whisper-service:
    image: opea/whisper:latest
    container_name: whisper-service
    ports:
      - "7066:7066"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HABANA_VISIBLE_DEVICES: all
      OMPI_MCA_btl_vader_single_copy_mechanism: none
    runtime: habana
    cap_add:
      - SYS_NICE
    restart: unless-stopped
  asr:
    image: opea/asr:latest
    container_name: asr-service
    ports:
      - "3001:9099"
    ipc: host
    environment:
      ASR_ENDPOINT: ${ASR_ENDPOINT}
  speecht5-service:
    image: opea/speecht5:latest
    container_name: speecht5-service
    ports:
      - "7055:7055"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HABANA_VISIBLE_DEVICES: all
      OMPI_MCA_btl_vader_single_copy_mechanism: none
    runtime: habana
    cap_add:
      - SYS_NICE
    restart: unless-stopped
  tts:
    image: opea/tts:latest
    container_name: tts-service
    ports:
      - "3002:9088"
    ipc: host
    environment:
      TTS_ENDPOINT: ${TTS_ENDPOINT}
  tgi-service:
    image: ghcr.io/huggingface/tgi-gaudi:2.0.1
    container_name: tgi-gaudi-server
    ports:
      - "3006:80"
    volumes:
      - "./data:/data"
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HF_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      HF_HUB_DISABLE_PROGRESS_BARS: 1
      HF_HUB_ENABLE_HF_TRANSFER: 0
      HABANA_VISIBLE_DEVICES: all
      OMPI_MCA_btl_vader_single_copy_mechanism: none
    runtime: habana
    cap_add:
      - SYS_NICE
    ipc: host
    command: --model-id ${LLM_MODEL_ID} --max-input-length 1024 --max-total-tokens 2048
  llm:
    image: opea/llm-tgi:latest
    container_name: llm-tgi-gaudi-server
    depends_on:
      - tgi-service
    ports:
      - "3007:9000"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      TGI_LLM_ENDPOINT: ${TGI_LLM_ENDPOINT}
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
    restart: unless-stopped
  audioqna-gaudi-backend-server:
    image: opea/audioqna:latest
    container_name: audioqna-gaudi-backend-server
    depends_on:
      - asr
      - llm
      - tts
    ports:
      - "3008:8888"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
      - MEGA_SERVICE_HOST_IP=${MEGA_SERVICE_HOST_IP}
      - ASR_SERVICE_HOST_IP=${ASR_SERVICE_HOST_IP}
      - ASR_SERVICE_PORT=${ASR_SERVICE_PORT}
      - LLM_SERVICE_HOST_IP=${LLM_SERVICE_HOST_IP}
      - LLM_SERVICE_PORT=${LLM_SERVICE_PORT}
      - TTS_SERVICE_HOST_IP=${TTS_SERVICE_HOST_IP}
      - TTS_SERVICE_PORT=${TTS_SERVICE_PORT}
    ipc: host
    restart: always

networks:
  default:
    driver: bridge
