# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# SPDX-License-Identifier: Apache-2.0

services:
  search-tei-embedding-service:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
    container_name: search-tei-embedding-server
    ports:
      - "3001:80"
    volumes:
      - "${MODEL_PATH}:/data"
    shm_size: 1g
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HF_TOKEN: ${SEARCH_HUGGINGFACEHUB_API_TOKEN}
      HUGGING_FACE_HUB_TOKEN: ${SEARCH_HUGGINGFACEHUB_API_TOKEN}
      HUGGINGFACEHUB_API_TOKEN: ${SEARCH_HUGGINGFACEHUB_API_TOKEN}
    command: --model-id ${SEARCH_EMBEDDING_MODEL_ID} --auto-truncate
  search-embedding:
    image: ${REGISTRY:-opea}/embedding:${TAG:-latest}
    container_name: search-embedding-server
    depends_on:
      - search-tei-embedding-service
    ports:
      - "3002:6000"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      TEI_EMBEDDING_HOST_IP: ${SEARCH_HOST_IP}
      TEI_EMBEDDING_ENDPOINT: ${SEARCH_TEI_EMBEDDING_ENDPOINT}
      HF_TOKEN: ${SEARCH_HUGGINGFACEHUB_API_TOKEN}
    restart: unless-stopped
  search-web-retriever:
    image: ${REGISTRY:-opea}/web-retriever:${TAG:-latest}
    container_name: search-web-retriever-server
    ports:
      - "3003:7077"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      TEI_EMBEDDING_ENDPOINT: ${SEARCH_TEI_EMBEDDING_ENDPOINT}
      GOOGLE_API_KEY: ${SEARCH_GOOGLE_API_KEY}
      GOOGLE_CSE_ID: ${SEARCH_GOOGLE_CSE_ID}
    restart: unless-stopped
  search-tei-reranking-service:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
    container_name: search-tei-reranking-server
    ports:
      - "3004:80"
    volumes:
      - "${MODEL_PATH}:/data"
    shm_size: 1g
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
    command: --model-id ${SEARCH_RERANK_MODEL_ID} --auto-truncate
  search-reranking:
    image: ${REGISTRY:-opea}/reranking:${TAG:-latest}
    container_name: search-reranking-server
    depends_on:
      - search-tei-reranking-service
    ports:
      - "3005:8000"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      TEI_RERANKING_ENDPOINT: ${SEARCH_TEI_RERANKING_ENDPOINT}
      HF_TOKEN: ${SEARCH_HUGGINGFACEHUB_API_TOKEN}
      HUGGING_FACE_HUB_TOKEN: ${SEARCH_HUGGINGFACEHUB_API_TOKEN}
      HUGGINGFACEHUB_API_TOKEN: ${SEARCH_HUGGINGFACEHUB_API_TOKEN}
    restart: unless-stopped
  search-tgi-service:
    image: ghcr.io/huggingface/text-generation-inference:2.3.1-rocm
    container_name: search-tgi-service
    ports:
      - "3006:80"
    volumes:
      - "${MODEL_PATH}:/data"
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HUGGING_FACE_HUB_TOKEN: ${SEARCH_HUGGINGFACEHUB_API_TOKEN}
      HUGGINGFACEHUB_API_TOKEN: ${SEARCH_HUGGINGFACEHUB_API_TOKEN}
    shm_size: 1g
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri/:/dev/dri/
    cap_add:
      - SYS_PTRACE
    group_add:
      - video
    security_opt:
      - seccomp:unconfined
    ipc: host
    command: --model-id ${SEARCH_LLM_MODEL_ID} --max-input-length 1024 --max-total-tokens 2048
  search-llm:
    image: ${REGISTRY:-opea}/llm-textgen:${TAG:-latest}
    container_name: search-llm-server
    depends_on:
      - search-tgi-service
    ports:
      - "3007:9000"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      TGI_LLM_ENDPOINT: ${SEARCH_TGI_LLM_ENDPOINT}
      HUGGINGFACEHUB_API_TOKEN: ${SEARCH_HUGGINGFACEHUB_API_TOKEN}
      LLM_ENDPOINT: ${SEARCH_TGI_LLM_ENDPOINT}
      LLM_MODEL_ID: ${SEARCH_LLM_MODEL_ID}
      LLM_MODEL: ${SEARCH_LLM_MODEL_ID}
      HF_TOKEN: ${SEARCH_HUGGINGFACEHUB_API_TOKEN}
      OPENAI_API_KEY: ${SEARCH_OPENAI_API_KEY}
    restart: unless-stopped
  search-backend-server:
    image: ${REGISTRY:-opea}/searchqna:${TAG:-latest}
    container_name: search-backend-server
    depends_on:
      - search-tei-embedding-service
      - search-embedding
      - search-web-retriever
      - search-tei-reranking-service
      - search-reranking
      - search-tgi-service
      - search-llm
    ports:
      - "${SEARCH_BACKEND_SERVICE_PORT:-3008}:8888"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
      - MEGA_SERVICE_HOST_IP=${SEARCH_MEGA_SERVICE_HOST_IP}
      - EMBEDDING_SERVICE_HOST_IP=${SEARCH_EMBEDDING_SERVICE_HOST_IP}
      - WEB_RETRIEVER_SERVICE_HOST_IP=${SEARCH_WEB_RETRIEVER_SERVICE_HOST_IP}
      - RERANK_SERVICE_HOST_IP=${SEARCH_RERANK_SERVICE_HOST_IP}
      - LLM_SERVICE_HOST_IP=${SEARCH_LLM_SERVICE_HOST_IP}
      - EMBEDDING_SERVICE_PORT=${SEARCH_EMBEDDING_SERVICE_PORT}
      - WEB_RETRIEVER_SERVICE_PORT=${SEARCH_WEB_RETRIEVER_SERVICE_PORT}
      - RERANK_SERVICE_PORT=${SEARCH_RERANK_SERVICE_PORT}
      - LLM_SERVICE_PORT=${SEARCH_LLM_SERVICE_PORT}
    ipc: host
    restart: always
  search-ui-server:
    image: ${REGISTRY:-opea}/searchqna-ui:${TAG:-latest}
    container_name: search-ui-server
    depends_on:
      - search-backend-server
    ports:
      - "${SEARCH_FRONTEND_SERVICE_PORT:-5173}:5173"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
      - BACKEND_BASE_URL=${SEARCH_BACKEND_SERVICE_ENDPOINT}
    ipc: host
    restart: always

networks:
  default:
    driver: bridge
