# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  text2image-backend-server:
    image: ${REGISTRY:-opea}/text2image:${TAG:-latest}
    container_name: text2image-backend-server
    ports:
      - "9379:9379"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
      - HUGGING_FACE_HUB_TOKEN=${HUGGINGFACEHUB_API_TOKEN}
      - MODEL=${MODEL}
    ipc: host
    restart: always
  text2image-ui-server:
    image: ${REGISTRY:-opea}/text2image-ui:${TAG:-latest}
    container_name: text2image-ui-server
    depends_on:
      - text2image-backend-server
    ports:
      - "5173:5173"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
      - BASE_URL=${BACKEND_SERVICE_ENDPOINT}
    ipc: host
    restart: always
  text2image-nginx-server:
    image: ${REGISTRY:-opea}/nginx:${TAG:-latest}
    container_name: text2image-nginx-server
    depends_on:
      - text2image-backend-server
      - text2image-ui-server
    ports:
      - "${NGINX_PORT:-80}:80"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
      - FRONTEND_SERVICE_IP=${FRONTEND_SERVICE_IP}
      - FRONTEND_SERVICE_PORT=${FRONTEND_SERVICE_PORT}
      - BACKEND_SERVICE_NAME=${BACKEND_SERVICE_NAME}
      - BACKEND_SERVICE_IP=${BACKEND_SERVICE_IP}
      - BACKEND_SERVICE_PORT=${BACKEND_SERVICE_PORT}
    ipc: host
    restart: always

networks:
  default:
    driver: bridge
