# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: docsum
description: The Helm chart to deploy DocSum
type: application
dependencies:
  - name: tgi
    version: 1.0.0
    repository: "file://../common/tgi"
  - name: llm-uservice
    version: 1.0.0
    repository: "file://../common/llm-uservice"
  - name: ui
    version: 1.0.0
    repository: "file://../common/ui"
    alias: docsum-ui
version: 1.0.0
appVersion: "v1.0"
