# Copyright (C) 2024 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: Apache-2.0

services:
  docsum-tgi-service:
    image: ghcr.io/huggingface/text-generation-inference:2.3.1-rocm
    container_name: docsum-tgi-service
    ports:
      - "${DOCSUM_TGI_SERVICE_PORT}:80"
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      TGI_LLM_ENDPOINT: "http://${HOST_IP}:${DOCSUM_TGI_SERVICE_PORT}"
      HUGGINGFACEHUB_API_TOKEN: ${DOCSUM_HUGGINGFACEHUB_API_TOKEN}
    volumes:
      - "/var/opea/docsum-service/data:/data"
    shm_size: 1g
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri/${DOCSUM_CARD_ID}:/dev/dri/${DOCSUM_CARD_ID}
      - /dev/dri/${DOCSUM_RENDER_ID}:/dev/dri/${DOCSUM_RENDER_ID}
    cap_add:
      - SYS_PTRACE
    group_add:
      - video
    security_opt:
      - seccomp:unconfined
    ipc: host
    command: --model-id ${DOCSUM_LLM_MODEL_ID}

  docsum-llm-server:
    image: ${REGISTRY:-opea}/llm-docsum-tgi:${TAG:-latest}
    container_name: docsum-llm-server
    depends_on:
      - docsum-tgi-service
    ports:
      - "${DOCSUM_LLM_SERVER_PORT}:9000"
    ipc: host
    group_add:
      - video
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri/${DOCSUM_CARD_ID}:/dev/dri/${DOCSUM_CARD_ID}
      - /dev/dri/${DOCSUM_RENDER_ID}:/dev/dri/${DOCSUM_RENDER_ID}
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      TGI_LLM_ENDPOINT: "http://${HOST_IP}:${DOCSUM_TGI_SERVICE_PORT}"
      HUGGINGFACEHUB_API_TOKEN: ${DOCSUM_HUGGINGFACEHUB_API_TOKEN}
    restart: unless-stopped

  whisper:
    image: ${REGISTRY:-opea}/whisper:${TAG:-latest}
    container_name: whisper-service
    ports:
      - "7066:7066"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
    restart: unless-stopped

  dataprep-audio2text:
    image: ${REGISTRY:-opea}/dataprep-audio2text:${TAG:-latest}
    container_name: dataprep-audio2text-service
    ports:
      - "9099:9099"
    ipc: host
    environment:
      A2T_ENDPOINT: ${A2T_ENDPOINT}

  dataprep-video2audio:
    image: ${REGISTRY:-opea}/dataprep-video2audio:${TAG:-latest}
    container_name: dataprep-video2audio-service
    ports:
      - "7078:7078"
    ipc: host
    environment:
      V2A_ENDPOINT: ${V2A_ENDPOINT}

  dataprep-multimedia2text:
    image: ${REGISTRY:-opea}/dataprep-multimedia2text:${TAG:-latest}
    container_name: dataprep-multimedia2text
    ports:
      - "7079:7079"
    ipc: host
    environment:
      V2A_ENDPOINT: ${V2A_ENDPOINT}
      A2T_ENDPOINT: ${A2T_ENDPOINT}

  docsum-backend-server:
    image: ${REGISTRY:-opea}/docsum:${TAG:-latest}
    container_name: docsum-backend-server
    depends_on:
      - docsum-tgi-service
      - docsum-llm-server
    ports:
      - "${DOCSUM_BACKEND_SERVER_PORT}:8888"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
      - MEGA_SERVICE_HOST_IP=${HOST_IP}
      - DATA_SERVICE_HOST_IP=${DATA_SERVICE_HOST_IP}
      - LLM_SERVICE_HOST_IP=${HOST_IP}
    ipc: host
    restart: always

  docsum-gradio-ui:
    image: ${REGISTRY:-opea}/docsum-gradio-ui:${TAG:-latest}
    container_name: docsum-ui-server
    depends_on:
      - docsum-backend-server
    ports:
      - "5173:5173"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
      - BACKEND_SERVICE_ENDPOINT=${BACKEND_SERVICE_ENDPOINT}
      - DOC_BASE_URL=${BACKEND_SERVICE_ENDPOINT}
    ipc: host
    restart: always

networks:
  default:
    driver: bridge
