
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0


services:
  vdms-vector-db:
    image: intellabs/vdms:latest
    container_name: vdms-vector-db
    ports:
      - "8001:55555"
  dataprep:
    image: opea/dataprep-vdms:latest
    container_name: dataprep-vdms-server
    depends_on:
      - vdms-vector-db
    ports:
      - "6007:6007"
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      VDMS_HOST: ${VDMS_HOST}
      VDMS_PORT: ${VDMS_PORT}
      INDEX_NAME: ${INDEX_NAME}
    entrypoint: sh -c 'sleep 15 && python ingest_videos.py'
    volumes:
      - /home/$USER/.cache/clip:/home/user/.cache/clip
      - /home/$USER/.cache/huggingface/hub:/home/user/.cache/huggingface/hub
  embedding:
    image: opea/embedding-multimodal:latest
    container_name: embedding-multimodal-server
    ports:
      - "6000:6000"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
    volumes:
      - /home/$USER/.cache/huggingface/hub:/home/user/.cache/huggingface/hub
    restart: unless-stopped
  retriever:
    image: opea/retriever-vdms:latest
    container_name: retriever-vdms-server
    depends_on:
      - vdms-vector-db
    ports:
      - "7000:7000"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      INDEX_NAME: ${INDEX_NAME}
      VDMS_HOST: ${VDMS_HOST}
      VDMS_PORT: ${VDMS_PORT}
      USECLIP: ${USECLIP}
    entrypoint: sh -c 'sleep 30 && python retriever_vdms.py'
    restart: unless-stopped
    volumes:
      - /home/$USER/.cache/huggingface/hub:/home/user/.cache/huggingface/hub
  reranking:
    image: opea/reranking-videoragqna:latest
    container_name: reranking-videoragqna-server
    ports:
      - "8000:8000"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      CHUNK_DURATION: ${CHUNK_DURATION}
      FILE_SERVER_ENDPOINT: ${DATAPREP_GET_FILE_ENDPOINT}
      DATAPREP_GET_VIDEO_LIST_ENDPOINT: ${DATAPREP_GET_VIDEO_LIST_ENDPOINT}
    restart: unless-stopped
  lvm-video-llama:
    image: opea/video-llama-lvm-server:latest
    container_name: video-llama-lvm-server
    ports:
      - "9009:9009"
    ipc: host
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
      llm_download: ${LLM_DOWNLOAD}
    volumes:
      - "/home/$USER/.cache:/home/user/.cache"
      - video-llama-model:/home/user/model
    restart: unless-stopped
  lvm:
    image: opea/lvm-video-llama:latest
    container_name: lvm-video-llama
    ports:
      - "9000:9000"
    ipc: host
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
      LVM_ENDPOINT: ${LVM_ENDPOINT}
    restart: unless-stopped
    depends_on:
      - lvm-video-llama
  videoragqna-xeon-backend-server:
    image: opea/videoragqna:latest
    container_name: videoragqna-xeon-backend-server
    depends_on:
      - vdms-vector-db
      - dataprep
      - embedding
      - retriever
      - reranking
      - lvm-video-llama
      - lvm
    ports:
      - "8888:8888"
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
      MEGA_SERVICE_HOST_IP: ${MEGA_SERVICE_HOST_IP}
      EMBEDDING_SERVICE_HOST_IP: ${EMBEDDING_SERVICE_HOST_IP}
      RETRIEVER_SERVICE_HOST_IP: ${RETRIEVER_SERVICE_HOST_IP}
      RERANK_SERVICE_HOST_IP: ${RERANK_SERVICE_HOST_IP}
      LVM_SERVICE_HOST_IP: ${LVM_SERVICE_HOST_IP}
    ipc: host
    restart: always
  videoragqna-xeon-ui-server:
    image: opea/videoragqna-ui:latest
    container_name: videoragqna-xeon-ui-server
    depends_on:
      - videoragqna-xeon-backend-server
    ports:
      - "5173:5173"
    environment:
      https_proxy: ${https_proxy}
      http_proxy: ${http_proxy}
      no_proxy: ${no_proxy}
      BACKEND_SERVICE_ENDPOINT: ${BACKEND_SERVICE_ENDPOINT}
      BACKEND_HEALTH_CHECK_ENDPOINT: ${BACKEND_HEALTH_CHECK_ENDPOINT}
    ipc: host
    restart: always
volumes:
  video-llama-model:
    external: true
networks:
  default:
    driver: bridge
