# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Check Requirements

on: [pull_request]

jobs:
  check-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Save PR requirements
        run: |
          find . -name "requirements.txt" -exec cat {} \; | \
              grep -v '^\s*#' | \
              grep -v '^\s*$' | \
              grep -v '^\s*-' | \
              sed 's/^\s*//' | \
              awk -F'[>=<]' '{print $1}' | \
              sort -u > pr-requirements.txt
          cat pr-requirements.txt

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main-branch

      - name: Save main branch requirements
        run: |
          find ./main-branch -name "requirements.txt" -exec cat {} \; | \
              grep -v '^\s*#' | \
              grep -v '^\s*$' | \
              grep -v '^\s*-' | \
              sed 's/^\s*//' | \
              awk -F'[>=<]' '{print $1}' | \
              sort -u > main-requirements.txt
          cat main-requirements.txt

      - name: Compare requirements
        env:
          URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          comm -23 pr-requirements.txt main-requirements.txt > added-packages.txt
          if [ -s added-packages.txt ]; then
            new_packages=$(cat added-packages.txt)
            echo "New packages found in PR: $new_packages"
            curl -X POST $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data "{ \"body\": \"New packages found in PR: $new_packages\" }"
          else
            echo "No new packages foundðŸ˜Š."
          fi
