# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Check Online Document Building
permissions: {}

on:
  pull_request:
    paths:
      - "**.md"
      - "**.rst"
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: GenAIComps

    - name: Checkout docs
      uses: actions/checkout@v4
      with:
        repository: opea-project/docs
        path: docs

    - name: Build Online Document
      shell: bash
      run: |
        echo "build online doc"
        cd docs
        bash scripts/build.sh
