# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: E2E test with GMC

on:
  pull_request:
    branches: ["main", "*rc"]
    types: [opened, reopened, ready_for_review, synchronize] # added `ready_for_review` since draft is skipped
    paths:
      - "**/kubernetes/**/gmc/**"
      - "**/tests/test_gmc**"
      - "!**.md"
      - "!**.txt"
      - "!**/kubernetes/**/manifests/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  job1:
    uses: ./.github/workflows/_get-test-matrix.yml
    with:
      diff_excluded_files: '.github|docker_compose|manifest|assets|*.md|*.txt'
      deploy_method: "gmc"

  gmc-test:
    needs: [job1]
    strategy:
      matrix: ${{ fromJSON(needs.job1.outputs.run_matrix) }}
    uses: ./.github/workflows/_gmc-e2e.yml
    with:
      example: ${{ matrix.example }}
      hardware: ${{ matrix.hardware }}
    secrets: inherit
