# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: E2E test with GMC

on:
  pull_request_target:
    branches: [main]
    types: [opened, reopened, ready_for_review, synchronize] # added `ready_for_review` since draft is skipped
    paths:
      - "**/kubernetes/**"
      - "**/tests/test_gmc**"
      - "!**.md"
      - "!**.txt"
      - "!**/kubernetes/manifests/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  job1:
    uses: ./.github/workflows/_get-test-matrix.yml
    with:
      diff_excluded_files: '.github|deprecated|docker|assets|*.md|*.txt'
      xeon_server_label: 'xeon'
      gaudi_server_label: 'gaudi'

  gmc-test:
    needs: [job1]
    strategy:
      matrix: ${{ fromJSON(needs.job1.outputs.run_matrix) }}
    uses: ./.github/workflows/_gmc-e2e.yml
    with:
      example: ${{ matrix.example }}
      hardware: ${{ matrix.hardware }}
    secrets: inherit
