# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: One Click CI Test

permissions:
  contents: read

on:
  pull_request:
    branches: ["main", "*rc", "one_click_dev"]
    types: [opened, reopened, synchronize] # added `ready_for_review` since draft is skipped
    paths:
      - "**/one_click_deploy/**"
      - "**/workflows/one-click-inputs-nobuild.json"
      - "**/workflows/pr-one-click.yml"
      - "**/workflows/_run-one-click.yml"

# If there is a new commit, the previous jobs will be canceled
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  one-click-test:
    strategy:
      matrix:
        deploy_method: ["docker", "k8s"]
        os: ["debian", "openeuler"]
      fail-fast: false
    uses: ./.github/workflows/_run-one-click.yml
    with:
      registry: "opea"
      tag: "ci"
      example: ChatQnA
      os: ${{ matrix.os }}
      hardware: xeon
      deploy_method: ${{ matrix.deploy_method }}
    secrets: inherit
